
project_id = "grcwlmltlcltmwbhdpky"

[functions.garmin-oauth]
verify_jwt = false

[functions.analyze-workout]
verify_jwt = true

[functions.send-error-notification]
verify_jwt = false

[functions.backfill-activities]
verify_jwt = true

[functions.garmin-activities-webhook]
verify_jwt = false

[functions.garmin-activity-details-webhook]
verify_jwt = false

[functions.garmin-deregistration]
verify_jwt = false

[functions.garmin-permissions]
verify_jwt = false

[functions.garmin-permissions-query]
verify_jwt = false

[functions.garmin-ping-webhook]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = true

[functions.reprocess-failed-webhooks]
verify_jwt = true

[functions.reprocess-stuck-webhooks]
verify_jwt = true

[functions.recover-specific-webhook]
verify_jwt = false

[functions.polar-activities-webhook]
verify_jwt = false
