
project_id = "grcwlmltlcltmwbhdpky"

[functions.garmin-oauth]
verify_jwt = false

[functions.analyze-workout]
verify_jwt = true

[functions.send-error-notification]
verify_jwt = false

[functions.backfill-activities]
verify_jwt = true

[functions.garmin-activities-webhook]
verify_jwt = false

[functions.garmin-deregistration]
verify_jwt = false
