
project_id = "grcwlmltlcltmwbhdpky"

[functions.direct-token-renewal]
verify_jwt = true

[functions.force-token-renewal]
verify_jwt = true

[functions.garmin-oauth]
verify_jwt = false

[functions.analyze-workout]
verify_jwt = true

[functions.send-error-notification]
verify_jwt = false

[functions.backfill-activities]
verify_jwt = true

[functions.garmin-activities-webhook]
verify_jwt = false

[functions.garmin-activity-details-webhook]
verify_jwt = false

[functions.garmin-deregistration]
verify_jwt = false

[functions.garmin-permissions]
verify_jwt = false

[functions.garmin-permissions-query]
verify_jwt = false

[functions.garmin-ping-webhook]
verify_jwt = false

[functions.garmin-sleep-webhook]
verify_jwt = false

[functions.sync-garmin-sleep]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.reprocess-failed-webhooks]
verify_jwt = true

[functions.reprocess-stuck-webhooks]
verify_jwt = true

[functions.recover-specific-webhook]
verify_jwt = false

[functions.polar-activities-webhook]
verify_jwt = false

[functions.check-polar-webhook]
verify_jwt = false

[functions.register-polar-webhook]
verify_jwt = false

[functions.verify-polar-webhook]
verify_jwt = false

[functions.test-polar-webhook-now]
verify_jwt = false

[functions.force-check-webhook]
verify_jwt = false

[functions.strava-config]
verify_jwt = false

[functions.strava-auth]
verify_jwt = true

[functions.strava-sync]
verify_jwt = true

[functions.scheduled-token-renewal]
verify_jwt = false

[functions.fix-cron-job]
verify_jwt = false

[functions.sync-polar-sleep]
verify_jwt = true
