project_id = "grcwlmltlcltmwbhdpky"

[functions.recover-polar-webhook-activities]
verify_jwt = false

[functions.recover-polar-activity-details]
verify_jwt = false

[functions.strava-token-refresh]
verify_jwt = true

[functions.welcome-email]
verify_jwt = false

[functions.test-welcome-email]
verify_jwt = true

[functions.test-email-simple]
verify_jwt = true

[functions.direct-token-renewal]
verify_jwt = true

[functions.force-token-renewal]
verify_jwt = true

[functions.garmin-oauth]
verify_jwt = false

[functions.analyze-workout]
verify_jwt = true

[functions.send-error-notification]
verify_jwt = false

[functions.backfill-activities]
verify_jwt = true

[functions.garmin-activities-webhook]
verify_jwt = false

[functions.garmin-activity-details-webhook]
verify_jwt = false

[functions.garmin-deregistration]
verify_jwt = false

[functions.garmin-permissions]
verify_jwt = false

[functions.garmin-permissions-query]
verify_jwt = false

[functions.garmin-ping-webhook]
verify_jwt = false

[functions.garmin-sleep-webhook]
verify_jwt = false

[functions.sync-garmin-sleep]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.reprocess-failed-webhooks]
verify_jwt = true

[functions.reprocess-stuck-webhooks]
verify_jwt = true

[functions.reprocess-sleep-notifications]
verify_jwt = true

[functions.recover-specific-webhook]
verify_jwt = false

[functions.polar-activities-webhook]
verify_jwt = false

[functions.check-polar-webhook]
verify_jwt = false

[functions.register-polar-webhook]
verify_jwt = false

[functions.verify-polar-webhook]
verify_jwt = false

[functions.test-polar-webhook-now]
verify_jwt = false

[functions.force-check-webhook]
verify_jwt = false

[functions.strava-config]
verify_jwt = false

[functions.strava-auth]
verify_jwt = true

[functions.strava-sync]
verify_jwt = true

[functions.scheduled-token-renewal]
verify_jwt = false

[functions.fix-cron-job]
verify_jwt = false

[functions.sync-polar-sleep]
verify_jwt = true

[functions.register-strava-webhook-simple]
verify_jwt = false

[functions.strava-webhook]
verify_jwt = false

[functions.garmin-user-metrics]
verify_jwt = false

[functions.run-polar-chr-manual]
verify_jwt = true

[functions.import-strava-gpx]
verify_jwt = true

[functions.get-polar-config]
verify_jwt = false

[functions.calculate-strava-performance-metrics]
verify_jwt = false

[functions.strava-activity-streams]
verify_jwt = false

[functions.scheduled-strava-token-renewal]
verify_jwt = false

[functions.calculate-fitness-score]
verify_jwt = true

[functions.build-activity-chart-cache]
verify_jwt = true

[functions.backfill-variation-analysis-runner]
verify_jwt = true

[functions.reprocess-garmin-details-errors-today]
verify_jwt = false

[functions.process-activity-chart-from-garmin-log]
verify_jwt = false

[functions.build-activity-chart-from-strava-streams]
verify_jwt = true

[functions.compute-athlete-level]
verify_jwt = true

[functions.analyze-goal-with-ai]
verify_jwt = true

[functions.classify-workouts]
verify_jwt = true
